// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: pkg/confidence/telemetry.proto

package confidence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoPlatform int32

const (
	ProtoPlatform_PROTO_PLATFORM_UNSPECIFIED ProtoPlatform = 0
	ProtoPlatform_PROTO_PLATFORM_JS_WEB      ProtoPlatform = 4
	ProtoPlatform_PROTO_PLATFORM_JS_SERVER   ProtoPlatform = 5
	ProtoPlatform_PROTO_PLATFORM_GO          ProtoPlatform = 7
)

// Enum value maps for ProtoPlatform.
var (
	ProtoPlatform_name = map[int32]string{
		0: "PROTO_PLATFORM_UNSPECIFIED",
		4: "PROTO_PLATFORM_JS_WEB",
		5: "PROTO_PLATFORM_JS_SERVER",
		7: "PROTO_PLATFORM_GO",
	}
	ProtoPlatform_value = map[string]int32{
		"PROTO_PLATFORM_UNSPECIFIED": 0,
		"PROTO_PLATFORM_JS_WEB":      4,
		"PROTO_PLATFORM_JS_SERVER":   5,
		"PROTO_PLATFORM_GO":          7,
	}
)

func (x ProtoPlatform) Enum() *ProtoPlatform {
	p := new(ProtoPlatform)
	*p = x
	return p
}

func (x ProtoPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_confidence_telemetry_proto_enumTypes[0].Descriptor()
}

func (ProtoPlatform) Type() protoreflect.EnumType {
	return &file_pkg_confidence_telemetry_proto_enumTypes[0]
}

func (x ProtoPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoPlatform.Descriptor instead.
func (ProtoPlatform) EnumDescriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{0}
}

type ProtoLibraryTraces_ProtoLibrary int32

const (
	ProtoLibraryTraces_PROTO_LIBRARY_UNSPECIFIED  ProtoLibraryTraces_ProtoLibrary = 0
	ProtoLibraryTraces_PROTO_LIBRARY_CONFIDENCE   ProtoLibraryTraces_ProtoLibrary = 1
	ProtoLibraryTraces_PROTO_LIBRARY_OPEN_FEATURE ProtoLibraryTraces_ProtoLibrary = 2
	ProtoLibraryTraces_PROTO_LIBRARY_REACT        ProtoLibraryTraces_ProtoLibrary = 3
)

// Enum value maps for ProtoLibraryTraces_ProtoLibrary.
var (
	ProtoLibraryTraces_ProtoLibrary_name = map[int32]string{
		0: "PROTO_LIBRARY_UNSPECIFIED",
		1: "PROTO_LIBRARY_CONFIDENCE",
		2: "PROTO_LIBRARY_OPEN_FEATURE",
		3: "PROTO_LIBRARY_REACT",
	}
	ProtoLibraryTraces_ProtoLibrary_value = map[string]int32{
		"PROTO_LIBRARY_UNSPECIFIED":  0,
		"PROTO_LIBRARY_CONFIDENCE":   1,
		"PROTO_LIBRARY_OPEN_FEATURE": 2,
		"PROTO_LIBRARY_REACT":        3,
	}
)

func (x ProtoLibraryTraces_ProtoLibrary) Enum() *ProtoLibraryTraces_ProtoLibrary {
	p := new(ProtoLibraryTraces_ProtoLibrary)
	*p = x
	return p
}

func (x ProtoLibraryTraces_ProtoLibrary) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoLibraryTraces_ProtoLibrary) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_confidence_telemetry_proto_enumTypes[1].Descriptor()
}

func (ProtoLibraryTraces_ProtoLibrary) Type() protoreflect.EnumType {
	return &file_pkg_confidence_telemetry_proto_enumTypes[1]
}

func (x ProtoLibraryTraces_ProtoLibrary) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoLibraryTraces_ProtoLibrary.Descriptor instead.
func (ProtoLibraryTraces_ProtoLibrary) EnumDescriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{1, 0}
}

type ProtoLibraryTraces_ProtoTraceId int32

const (
	ProtoLibraryTraces_PROTO_TRACE_ID_UNSPECIFIED        ProtoLibraryTraces_ProtoTraceId = 0
	ProtoLibraryTraces_PROTO_TRACE_ID_RESOLVE_LATENCY    ProtoLibraryTraces_ProtoTraceId = 1
	ProtoLibraryTraces_PROTO_TRACE_ID_STALE_FLAG         ProtoLibraryTraces_ProtoTraceId = 2
	ProtoLibraryTraces_PROTO_TRACE_ID_FLAG_TYPE_MISMATCH ProtoLibraryTraces_ProtoTraceId = 3
	ProtoLibraryTraces_PROTO_TRACE_ID_WITH_CONTEXT       ProtoLibraryTraces_ProtoTraceId = 4
)

// Enum value maps for ProtoLibraryTraces_ProtoTraceId.
var (
	ProtoLibraryTraces_ProtoTraceId_name = map[int32]string{
		0: "PROTO_TRACE_ID_UNSPECIFIED",
		1: "PROTO_TRACE_ID_RESOLVE_LATENCY",
		2: "PROTO_TRACE_ID_STALE_FLAG",
		3: "PROTO_TRACE_ID_FLAG_TYPE_MISMATCH",
		4: "PROTO_TRACE_ID_WITH_CONTEXT",
	}
	ProtoLibraryTraces_ProtoTraceId_value = map[string]int32{
		"PROTO_TRACE_ID_UNSPECIFIED":        0,
		"PROTO_TRACE_ID_RESOLVE_LATENCY":    1,
		"PROTO_TRACE_ID_STALE_FLAG":         2,
		"PROTO_TRACE_ID_FLAG_TYPE_MISMATCH": 3,
		"PROTO_TRACE_ID_WITH_CONTEXT":       4,
	}
)

func (x ProtoLibraryTraces_ProtoTraceId) Enum() *ProtoLibraryTraces_ProtoTraceId {
	p := new(ProtoLibraryTraces_ProtoTraceId)
	*p = x
	return p
}

func (x ProtoLibraryTraces_ProtoTraceId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoLibraryTraces_ProtoTraceId) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_confidence_telemetry_proto_enumTypes[2].Descriptor()
}

func (ProtoLibraryTraces_ProtoTraceId) Type() protoreflect.EnumType {
	return &file_pkg_confidence_telemetry_proto_enumTypes[2]
}

func (x ProtoLibraryTraces_ProtoTraceId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoLibraryTraces_ProtoTraceId.Descriptor instead.
func (ProtoLibraryTraces_ProtoTraceId) EnumDescriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{1, 1}
}

type ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus int32

const (
	ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_PROTO_STATUS_UNSPECIFIED ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus = 0
	ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_PROTO_STATUS_SUCCESS     ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus = 1
	ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_PROTO_STATUS_ERROR       ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus = 2
	ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_PROTO_STATUS_TIMEOUT     ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus = 3
	ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_PROTO_STATUS_CACHED      ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus = 4
)

// Enum value maps for ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus.
var (
	ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus_name = map[int32]string{
		0: "PROTO_STATUS_UNSPECIFIED",
		1: "PROTO_STATUS_SUCCESS",
		2: "PROTO_STATUS_ERROR",
		3: "PROTO_STATUS_TIMEOUT",
		4: "PROTO_STATUS_CACHED",
	}
	ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus_value = map[string]int32{
		"PROTO_STATUS_UNSPECIFIED": 0,
		"PROTO_STATUS_SUCCESS":     1,
		"PROTO_STATUS_ERROR":       2,
		"PROTO_STATUS_TIMEOUT":     3,
		"PROTO_STATUS_CACHED":      4,
	}
)

func (x ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus) Enum() *ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus {
	p := new(ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus)
	*p = x
	return p
}

func (x ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_confidence_telemetry_proto_enumTypes[3].Descriptor()
}

func (ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus) Type() protoreflect.EnumType {
	return &file_pkg_confidence_telemetry_proto_enumTypes[3]
}

func (x ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus.Descriptor instead.
func (ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{1, 0, 1, 0}
}

type ProtoMonitoring struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LibraryTraces []*ProtoLibraryTraces `protobuf:"bytes,1,rep,name=library_traces,json=libraryTraces,proto3" json:"library_traces,omitempty"`
	Platform      ProtoPlatform         `protobuf:"varint,2,opt,name=platform,proto3,enum=confidence.telemetry.v1.ProtoPlatform" json:"platform,omitempty"`
}

func (x *ProtoMonitoring) Reset() {
	*x = ProtoMonitoring{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_confidence_telemetry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoMonitoring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMonitoring) ProtoMessage() {}

func (x *ProtoMonitoring) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_confidence_telemetry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMonitoring.ProtoReflect.Descriptor instead.
func (*ProtoMonitoring) Descriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMonitoring) GetLibraryTraces() []*ProtoLibraryTraces {
	if x != nil {
		return x.LibraryTraces
	}
	return nil
}

func (x *ProtoMonitoring) GetPlatform() ProtoPlatform {
	if x != nil {
		return x.Platform
	}
	return ProtoPlatform_PROTO_PLATFORM_UNSPECIFIED
}

type ProtoLibraryTraces struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Library        ProtoLibraryTraces_ProtoLibrary  `protobuf:"varint,1,opt,name=library,proto3,enum=confidence.telemetry.v1.ProtoLibraryTraces_ProtoLibrary" json:"library,omitempty"`
	LibraryVersion string                           `protobuf:"bytes,2,opt,name=library_version,json=libraryVersion,proto3" json:"library_version,omitempty"`
	Traces         []*ProtoLibraryTraces_ProtoTrace `protobuf:"bytes,3,rep,name=traces,proto3" json:"traces,omitempty"`
}

func (x *ProtoLibraryTraces) Reset() {
	*x = ProtoLibraryTraces{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_confidence_telemetry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoLibraryTraces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLibraryTraces) ProtoMessage() {}

func (x *ProtoLibraryTraces) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_confidence_telemetry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLibraryTraces.ProtoReflect.Descriptor instead.
func (*ProtoLibraryTraces) Descriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoLibraryTraces) GetLibrary() ProtoLibraryTraces_ProtoLibrary {
	if x != nil {
		return x.Library
	}
	return ProtoLibraryTraces_PROTO_LIBRARY_UNSPECIFIED
}

func (x *ProtoLibraryTraces) GetLibraryVersion() string {
	if x != nil {
		return x.LibraryVersion
	}
	return ""
}

func (x *ProtoLibraryTraces) GetTraces() []*ProtoLibraryTraces_ProtoTrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type ProtoLibraryTraces_ProtoTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id ProtoLibraryTraces_ProtoTraceId `protobuf:"varint,1,opt,name=id,proto3,enum=confidence.telemetry.v1.ProtoLibraryTraces_ProtoTraceId" json:"id,omitempty"`
	// DEPRECATED
	MillisecondDuration *uint64 `protobuf:"varint,2,opt,name=millisecond_duration,json=millisecondDuration,proto3,oneof" json:"millisecond_duration,omitempty"`
	// Types that are assignable to Trace:
	//
	//	*ProtoLibraryTraces_ProtoTrace_RequestTrace
	//	*ProtoLibraryTraces_ProtoTrace_CountTrace
	Trace isProtoLibraryTraces_ProtoTrace_Trace `protobuf_oneof:"trace"`
}

func (x *ProtoLibraryTraces_ProtoTrace) Reset() {
	*x = ProtoLibraryTraces_ProtoTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_confidence_telemetry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoLibraryTraces_ProtoTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLibraryTraces_ProtoTrace) ProtoMessage() {}

func (x *ProtoLibraryTraces_ProtoTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_confidence_telemetry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLibraryTraces_ProtoTrace.ProtoReflect.Descriptor instead.
func (*ProtoLibraryTraces_ProtoTrace) Descriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ProtoLibraryTraces_ProtoTrace) GetId() ProtoLibraryTraces_ProtoTraceId {
	if x != nil {
		return x.Id
	}
	return ProtoLibraryTraces_PROTO_TRACE_ID_UNSPECIFIED
}

func (x *ProtoLibraryTraces_ProtoTrace) GetMillisecondDuration() uint64 {
	if x != nil && x.MillisecondDuration != nil {
		return *x.MillisecondDuration
	}
	return 0
}

func (m *ProtoLibraryTraces_ProtoTrace) GetTrace() isProtoLibraryTraces_ProtoTrace_Trace {
	if m != nil {
		return m.Trace
	}
	return nil
}

func (x *ProtoLibraryTraces_ProtoTrace) GetRequestTrace() *ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace {
	if x, ok := x.GetTrace().(*ProtoLibraryTraces_ProtoTrace_RequestTrace); ok {
		return x.RequestTrace
	}
	return nil
}

func (x *ProtoLibraryTraces_ProtoTrace) GetCountTrace() *ProtoLibraryTraces_ProtoTrace_ProtoCountTrace {
	if x, ok := x.GetTrace().(*ProtoLibraryTraces_ProtoTrace_CountTrace); ok {
		return x.CountTrace
	}
	return nil
}

type isProtoLibraryTraces_ProtoTrace_Trace interface {
	isProtoLibraryTraces_ProtoTrace_Trace()
}

type ProtoLibraryTraces_ProtoTrace_RequestTrace struct {
	RequestTrace *ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace `protobuf:"bytes,3,opt,name=request_trace,json=requestTrace,proto3,oneof"`
}

type ProtoLibraryTraces_ProtoTrace_CountTrace struct {
	CountTrace *ProtoLibraryTraces_ProtoTrace_ProtoCountTrace `protobuf:"bytes,4,opt,name=count_trace,json=countTrace,proto3,oneof"`
}

func (*ProtoLibraryTraces_ProtoTrace_RequestTrace) isProtoLibraryTraces_ProtoTrace_Trace() {}

func (*ProtoLibraryTraces_ProtoTrace_CountTrace) isProtoLibraryTraces_ProtoTrace_Trace() {}

type ProtoLibraryTraces_ProtoTrace_ProtoCountTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProtoLibraryTraces_ProtoTrace_ProtoCountTrace) Reset() {
	*x = ProtoLibraryTraces_ProtoTrace_ProtoCountTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_confidence_telemetry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoLibraryTraces_ProtoTrace_ProtoCountTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLibraryTraces_ProtoTrace_ProtoCountTrace) ProtoMessage() {}

func (x *ProtoLibraryTraces_ProtoTrace_ProtoCountTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_confidence_telemetry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLibraryTraces_ProtoTrace_ProtoCountTrace.ProtoReflect.Descriptor instead.
func (*ProtoLibraryTraces_ProtoTrace_ProtoCountTrace) Descriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{1, 0, 0}
}

type ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MillisecondDuration uint64                                                      `protobuf:"varint,1,opt,name=millisecond_duration,json=millisecondDuration,proto3" json:"millisecond_duration,omitempty"`
	Status              ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus `protobuf:"varint,2,opt,name=status,proto3,enum=confidence.telemetry.v1.ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus" json:"status,omitempty"`
}

func (x *ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace) Reset() {
	*x = ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_confidence_telemetry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace) ProtoMessage() {}

func (x *ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_confidence_telemetry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace.ProtoReflect.Descriptor instead.
func (*ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace) Descriptor() ([]byte, []int) {
	return file_pkg_confidence_telemetry_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace) GetMillisecondDuration() uint64 {
	if x != nil {
		return x.MillisecondDuration
	}
	return 0
}

func (x *ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace) GetStatus() ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus {
	if x != nil {
		return x.Status
	}
	return ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_PROTO_STATUS_UNSPECIFIED
}

var File_pkg_confidence_telemetry_proto protoreflect.FileDescriptor

var file_pkg_confidence_telemetry_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x17, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x22, 0xa9, 0x01, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x52, 0x0a,
	0x0e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x73, 0x52, 0x0d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x72, 0x61, 0x63, 0x65,
	0x73, 0x12, 0x42, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x90, 0x0a, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x07,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x07, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79,
	0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x72, 0x79, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x06, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x1a, 0xe9, 0x05, 0x0a, 0x0a, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x72, 0x61, 0x63, 0x65,
	0x73, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x36, 0x0a, 0x14, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x48, 0x01, 0x52, 0x13, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x6f, 0x0a, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x48, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x74,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x0b, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x46, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x1a, 0x11, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x1a, 0xc7, 0x02, 0x0a, 0x11, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12,
	0x31, 0x0a, 0x14, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x6d,
	0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x6c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x54, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x90, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1c, 0x0a, 0x18, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18,
	0x0a, 0x14, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x52, 0x4f, 0x54,
	0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02,
	0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x41, 0x43, 0x48, 0x45,
	0x44, 0x10, 0x04, 0x42, 0x07, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x42, 0x17, 0x0a, 0x15,
	0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x84, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f,
	0x4c, 0x49, 0x42, 0x52, 0x41, 0x52, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x4c,
	0x49, 0x42, 0x52, 0x41, 0x52, 0x59, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x44, 0x45, 0x4e, 0x43,
	0x45, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x4c, 0x49, 0x42,
	0x52, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x46, 0x45, 0x41, 0x54, 0x55, 0x52,
	0x45, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x4c, 0x49, 0x42,
	0x52, 0x41, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x41, 0x43, 0x54, 0x10, 0x03, 0x22, 0xb9, 0x01, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x1a, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x45, 0x5f, 0x49, 0x44, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x22, 0x0a,
	0x1e, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x45, 0x5f, 0x49, 0x44, 0x5f,
	0x52, 0x45, 0x53, 0x4f, 0x4c, 0x56, 0x45, 0x5f, 0x4c, 0x41, 0x54, 0x45, 0x4e, 0x43, 0x59, 0x10,
	0x01, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x45,
	0x5f, 0x49, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x4c, 0x45, 0x5f, 0x46, 0x4c, 0x41, 0x47, 0x10, 0x02,
	0x12, 0x25, 0x0a, 0x21, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x45, 0x5f,
	0x49, 0x44, 0x5f, 0x46, 0x4c, 0x41, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x49, 0x53,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x03, 0x12, 0x1f, 0x0a, 0x1b, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x5f, 0x54, 0x52, 0x41, 0x43, 0x45, 0x5f, 0x49, 0x44, 0x5f, 0x57, 0x49, 0x54, 0x48, 0x5f, 0x43,
	0x4f, 0x4e, 0x54, 0x45, 0x58, 0x54, 0x10, 0x04, 0x2a, 0x7f, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1e, 0x0a, 0x1a, 0x50, 0x52, 0x4f,
	0x54, 0x4f, 0x5f, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x52, 0x4f,
	0x54, 0x4f, 0x5f, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x4a, 0x53, 0x5f, 0x57,
	0x45, 0x42, 0x10, 0x04, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x50, 0x4c,
	0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x4a, 0x53, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52,
	0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x50, 0x4c, 0x41, 0x54,
	0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x47, 0x4f, 0x10, 0x07, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67,
	0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_confidence_telemetry_proto_rawDescOnce sync.Once
	file_pkg_confidence_telemetry_proto_rawDescData = file_pkg_confidence_telemetry_proto_rawDesc
)

func file_pkg_confidence_telemetry_proto_rawDescGZIP() []byte {
	file_pkg_confidence_telemetry_proto_rawDescOnce.Do(func() {
		file_pkg_confidence_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_confidence_telemetry_proto_rawDescData)
	})
	return file_pkg_confidence_telemetry_proto_rawDescData
}

var file_pkg_confidence_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_confidence_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_confidence_telemetry_proto_goTypes = []interface{}{
	(ProtoPlatform)(0),                                               // 0: confidence.telemetry.v1.ProtoPlatform
	(ProtoLibraryTraces_ProtoLibrary)(0),                             // 1: confidence.telemetry.v1.ProtoLibraryTraces.ProtoLibrary
	(ProtoLibraryTraces_ProtoTraceId)(0),                             // 2: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTraceId
	(ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace_ProtoStatus)(0), // 3: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.ProtoRequestTrace.ProtoStatus
	(*ProtoMonitoring)(nil),                                          // 4: confidence.telemetry.v1.ProtoMonitoring
	(*ProtoLibraryTraces)(nil),                                       // 5: confidence.telemetry.v1.ProtoLibraryTraces
	(*ProtoLibraryTraces_ProtoTrace)(nil),                            // 6: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace
	(*ProtoLibraryTraces_ProtoTrace_ProtoCountTrace)(nil),            // 7: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.ProtoCountTrace
	(*ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace)(nil),          // 8: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.ProtoRequestTrace
}
var file_pkg_confidence_telemetry_proto_depIdxs = []int32{
	5, // 0: confidence.telemetry.v1.ProtoMonitoring.library_traces:type_name -> confidence.telemetry.v1.ProtoLibraryTraces
	0, // 1: confidence.telemetry.v1.ProtoMonitoring.platform:type_name -> confidence.telemetry.v1.ProtoPlatform
	1, // 2: confidence.telemetry.v1.ProtoLibraryTraces.library:type_name -> confidence.telemetry.v1.ProtoLibraryTraces.ProtoLibrary
	6, // 3: confidence.telemetry.v1.ProtoLibraryTraces.traces:type_name -> confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace
	2, // 4: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.id:type_name -> confidence.telemetry.v1.ProtoLibraryTraces.ProtoTraceId
	8, // 5: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.request_trace:type_name -> confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.ProtoRequestTrace
	7, // 6: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.count_trace:type_name -> confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.ProtoCountTrace
	3, // 7: confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.ProtoRequestTrace.status:type_name -> confidence.telemetry.v1.ProtoLibraryTraces.ProtoTrace.ProtoRequestTrace.ProtoStatus
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_confidence_telemetry_proto_init() }
func file_pkg_confidence_telemetry_proto_init() {
	if File_pkg_confidence_telemetry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_confidence_telemetry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoMonitoring); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_confidence_telemetry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoLibraryTraces); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_confidence_telemetry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoLibraryTraces_ProtoTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_confidence_telemetry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoLibraryTraces_ProtoTrace_ProtoCountTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_confidence_telemetry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoLibraryTraces_ProtoTrace_ProtoRequestTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_confidence_telemetry_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ProtoLibraryTraces_ProtoTrace_RequestTrace)(nil),
		(*ProtoLibraryTraces_ProtoTrace_CountTrace)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_confidence_telemetry_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_confidence_telemetry_proto_goTypes,
		DependencyIndexes: file_pkg_confidence_telemetry_proto_depIdxs,
		EnumInfos:         file_pkg_confidence_telemetry_proto_enumTypes,
		MessageInfos:      file_pkg_confidence_telemetry_proto_msgTypes,
	}.Build()
	File_pkg_confidence_telemetry_proto = out.File
	file_pkg_confidence_telemetry_proto_rawDesc = nil
	file_pkg_confidence_telemetry_proto_goTypes = nil
	file_pkg_confidence_telemetry_proto_depIdxs = nil
}
